# NODES

application=['SK_ID_CURR','CODE_GENDER','CNT_CHILDREN','NAME_INCOME_TYPE','NAME_EDUCATION_TYPE','NAME_FAMILY_TYPE','NAME_HOUSING_TYPE','OCCUPATION_TYPE']

In [1]:
import pandas as pd
import sys
import numpy as np
import os

In [2]:

# Create the folder if it already doesn't exist# Create  
if not os.path.exists('graph_csv_1000k'):
    os.makedirs('graph_csv_1000k')

# Application.csv

In [3]:
data=pd.read_csv("data/application_train.csv",index_col=0)

In [4]:
data=data.iloc[0:1000]
# list(data.columns)

In [5]:
attr_list =['SK_ID_CURR','CODE_GENDER','CNT_CHILDREN','NAME_INCOME_TYPE','NAME_EDUCATION_TYPE','NAME_FAMILY_STATUS','NAME_HOUSING_TYPE','OCCUPATION_TYPE']
attr_set = set(attr_list)

In [6]:
df_export = data

In [7]:
# df.to_csv('graph_csv/application.csv',index_label="applicationId:SK_ID_CURR(Applications)",float_format="%.10g")
df_export.to_csv('graph_csv_1000k/application.csv',index=True,index_label="SK_ID_CURR:ID(Application)")

In [8]:
df_export.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 100002 to 101156
Columns: 121 entries, TARGET to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(40), object(16)
memory usage: 953.1+ KB

# previous.application.csv

In [9]:
prev=pd.read_csv('data/previous_application.csv',index_col=0)

/usr/local/lib/python3.6/site-packages/numpy/lib/arraysetops.py:472: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [72]:
currId=list(df_export.index)
df_prev=prev[prev['SK_ID_CURR'].isin(currId)] 
df_prev.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4769 entries, 1891648 to 2276384
Data columns (total 36 columns):
SK_ID_CURR                     4769 non-null int64
NAME_CONTRACT_TYPE             4769 non-null object
AMT_ANNUITY                    3692 non-null float64
AMT_APPLICATION                4769 non-null float64
AMT_CREDIT                     4769 non-null float64
AMT_DOWN_PAYMENT               2235 non-null float64
AMT_GOODS_PRICE                3681 non-null float64
WEEKDAY_APPR_PROCESS_START     4769 non-null object
HOUR_APPR_PROCESS_START        4769 non-null int64
FLAG_LAST_APPL_PER_CONTRACT    4769 non-null object
NFLAG_LAST_APPL_IN_DAY         4769 non-null int64
RATE_DOWN_PAYMENT              2235 non-null float64
RATE_INTEREST_PRIMARY          12 non-null float64
RATE_INTEREST_PRIVILEGED       12 non-null float64
NAME_CASH_LOAN_PURPOSE         4769 non-null object
NAME_CONTRACT_STATUS           4769 non-null object
DAYS_DECISION                  4769 non-null int64
NAME_PAYMENT_TYPE              4769 non-null object
CODE_REJECT_REASON             4769 non-null object
NAME_TYPE_SUITE                2454 non-null object
NAME_CLIENT_TYPE               4769 non-null object
NAME_GOODS_CATEGORY            4769 non-null object
NAME_PORTFOLIO                 4769 non-null object
NAME_PRODUCT_TYPE              4769 non-null object
CHANNEL_TYPE                   4769 non-null object
SELLERPLACE_AREA               4769 non-null int64
NAME_SELLER_INDUSTRY           4769 non-null object
CNT_PAYMENT                    3692 non-null float64
NAME_YIELD_GROUP               4769 non-null object
PRODUCT_COMBINATION            4767 non-null object
DAYS_FIRST_DRAWING             2842 non-null float64
DAYS_FIRST_DUE                 2842 non-null float64
DAYS_LAST_DUE_1ST_VERSION      2842 non-null float64
DAYS_LAST_DUE                  2842 non-null float64
DAYS_TERMINATION               2842 non-null float64
NFLAG_INSURED_ON_APPROVAL      2842 non-null float64
dtypes: float64(15), int64(5), object(16)
memory usage: 1.3+ MB

In [73]:
currId=set(currId)
b=set(df_prev['SK_ID_CURR'])
b-currId

set()

In [74]:
df_prev.to_csv('graph_csv_1000k/previous_application.csv',index=True,index_label="SK_ID_PREV:ID(Previous_Application)")
df_prev.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4769 entries, 1891648 to 2276384
Data columns (total 36 columns):
SK_ID_CURR                     4769 non-null int64
NAME_CONTRACT_TYPE             4769 non-null object
AMT_ANNUITY                    3692 non-null float64
AMT_APPLICATION                4769 non-null float64
AMT_CREDIT                     4769 non-null float64
AMT_DOWN_PAYMENT               2235 non-null float64
AMT_GOODS_PRICE                3681 non-null float64
WEEKDAY_APPR_PROCESS_START     4769 non-null object
HOUR_APPR_PROCESS_START        4769 non-null int64
FLAG_LAST_APPL_PER_CONTRACT    4769 non-null object
NFLAG_LAST_APPL_IN_DAY         4769 non-null int64
RATE_DOWN_PAYMENT              2235 non-null float64
RATE_INTEREST_PRIMARY          12 non-null float64
RATE_INTEREST_PRIVILEGED       12 non-null float64
NAME_CASH_LOAN_PURPOSE         4769 non-null object
NAME_CONTRACT_STATUS           4769 non-null object
DAYS_DECISION                  4769 non-null int64
NAME_PAYMENT_TYPE              4769 non-null object
CODE_REJECT_REASON             4769 non-null object
NAME_TYPE_SUITE                2454 non-null object
NAME_CLIENT_TYPE               4769 non-null object
NAME_GOODS_CATEGORY            4769 non-null object
NAME_PORTFOLIO                 4769 non-null object
NAME_PRODUCT_TYPE              4769 non-null object
CHANNEL_TYPE                   4769 non-null object
SELLERPLACE_AREA               4769 non-null int64
NAME_SELLER_INDUSTRY           4769 non-null object
CNT_PAYMENT                    3692 non-null float64
NAME_YIELD_GROUP               4769 non-null object
PRODUCT_COMBINATION            4767 non-null object
DAYS_FIRST_DRAWING             2842 non-null float64
DAYS_FIRST_DUE                 2842 non-null float64
DAYS_LAST_DUE_1ST_VERSION      2842 non-null float64
DAYS_LAST_DUE                  2842 non-null float64
DAYS_TERMINATION               2842 non-null float64
NFLAG_INSURED_ON_APPROVAL      2842 non-null float64
dtypes: float64(15), int64(5), object(16)
memory usage: 1.3+ MB

In [75]:
df_prev.index=='2582071'

False

# Bureau.csv

In [ ]:
bureaudata=pd.read_csv("data/bureau.csv",index_col=1)

In [40]:
currId=list(df_export.index)
currId

[100002,
 100003,
 100004,
 100006,
 100007,
 100008,
 100009,
 100010,
 100011,
 100012,
 100014,
 100015,
 100016,
 100017,
 100018,
 100019,
 100020,
 100021,
 100022,
 100023,
 100024,
 100025,
 100026,
 100027,
 100029,
 100030,
 100031,
 100032,
 100033,
 100034,
 100035,
 100036,
 100037,
 100039,
 100040,
 100041,
 100043,
 100044,
 100045,
 100046,
 100047,
 100048,
 100049,
 100050,
 100051,
 100052,
 100053,
 100054,
 100055,
 100056,
 100058,
 100059,
 100060,
 100061,
 100062,
 100063,
 100064,
 100068,
 100069,
 100070,
 100071,
 100072,
 100073,
 100075,
 100076,
 100077,
 100078,
 100079,
 100080,
 100081,
 100082,
 100083,
 100084,
 100085,
 100086,
 100087,
 100088,
 100089,
 100093,
 100094,
 100095,
 100096,
 100097,
 100098,
 100099,
 100100,
 100101,
 100102,
 100103,
 100104,
 100105,
 100108,
 100110,
 100111,
 100112,
 100113,
 100114,
 100115,
 100116,
 100118,
 100119,
 100120,
 100121,
 100122,
 100123,
 100124,
 100125,
 100126,
 100127,
 100129,
 100130,
 100131,
 100132,
 100133,
 100134,
 100135,
 100136,
 100137,
 100138,
 100139,
 100140,
 100142,
 100143,
 100144,
 100145,
 100146,
 100147,
 100148,
 100149,
 100151,
 100152,
 100153,
 100154,
 100155,
 100156,
 100157,
 100158,
 100159,
 100160,
 100161,
 100162,
 100163,
 100164,
 100165,
 100166,
 100167,
 100173,
 100174,
 100175,
 100176,
 100177,
 100178,
 100179,
 100180,
 100181,
 100182,
 100183,
 100185,
 100186,
 100188,
 100189,
 100190,
 100191,
 100192,
 100193,
 100194,
 100195,
 100196,
 100197,
 100198,
 100199,
 100200,
 100201,
 100202,
 100203,
 100204,
 100205,
 100206,
 100207,
 100208,
 100209,
 100210,
 100211,
 100213,
 100214,
 100215,
 100216,
 100217,
 100218,
 100219,
 100220,
 100221,
 100224,
 100225,
 100226,
 100227,
 100228,
 100229,
 100230,
 100231,
 100233,
 100234,
 100235,
 100236,
 100237,
 100238,
 100239,
 100240,
 100242,
 100243,
 100244,
 100246,
 100247,
 100248,
 100249,
 100250,
 100251,
 100252,
 100254,
 100255,
 100257,
 100258,
 100259,
 100260,
 100261,
 100262,
 100263,
 100264,
 100265,
 100266,
 100267,
 100268,
 100269,
 100270,
 100272,
 100273,
 100274,
 100275,
 100276,
 100277,
 100279,
 100281,
 100282,
 100283,
 100284,
 100285,
 100286,
 100287,
 100288,
 100289,
 100290,
 100291,
 100292,
 100293,
 100294,
 100295,
 100296,
 100297,
 100298,
 100299,
 100300,
 100301,
 100302,
 100303,
 100304,
 100305,
 100307,
 100308,
 100309,
 100310,
 100313,
 100314,
 100315,
 100316,
 100317,
 100318,
 100319,
 100320,
 100321,
 100322,
 100323,
 100324,
 100325,
 100326,
 100327,
 100328,
 100329,
 100332,
 100333,
 100334,
 100335,
 100336,
 100337,
 100338,
 100339,
 100340,
 100341,
 100342,
 100343,
 100344,
 100345,
 100346,
 100347,
 100348,
 100349,
 100350,
 100351,
 100353,
 100354,
 100355,
 100356,
 100357,
 100359,
 100360,
 100361,
 100362,
 100363,
 100364,
 100365,
 100366,
 100368,
 100369,
 100370,
 100371,
 100372,
 100373,
 100374,
 100375,
 100376,
 100377,
 100378,
 100379,
 100380,
 100381,
 100383,
 100387,
 100388,
 100389,
 100390,
 100391,
 100392,
 100393,
 100394,
 100395,
 100396,
 100397,
 100398,
 100400,
 100401,
 100402,
 100403,
 100405,
 100406,
 100407,
 100408,
 100409,
 100410,
 100411,
 100412,
 100413,
 100414,
 100415,
 100417,
 100418,
 100419,
 100420,
 100421,
 100423,
 100424,
 100425,
 100427,
 100428,
 100429,
 100430,
 100431,
 100432,
 100433,
 100434,
 100435,
 100436,
 100437,
 100439,
 100440,
 100441,
 100442,
 100443,
 100448,
 100449,
 100451,
 100452,
 100453,
 100454,
 100455,
 100456,
 100457,
 100458,
 100459,
 100460,
 100461,
 100462,
 100463,
 100464,
 100465,
 100467,
 100468,
 100469,
 100470,
 100471,
 100472,
 100473,
 100474,
 100475,
 100476,
 100477,
 100478,
 100479,
 100480,
 100481,
 100482,
 100485,
 100486,
 100487,
 100488,
 100489,
 100490,
 100491,
 100492,
 100493,
 100495,
 100496,
 100497,
 100498,
 100499,
 100500,
 100501,
 100502,
 100503,
 100504,
 100505,
 100506,
 100507,
 100508,
 100509,
 100511,
 100513,
 100514,
 100515,
 100516,
 100518,
 100519,
 100520,
 100521,
 100522,
 100523,
 100524,
 100525,
 100526,
 100527,
 100528,
 100529,
 100530,
 100531,
 100532,
 100533,
 100534,
 100535,
 100536,
 100537,
 100538,
 100539,
 100540,
 100541,
 100542,
 100543,
 100544,
 100545,
 100546,
 100547,
 100549,
 100550,
 100554,
 100555,
 100556,
 100557,
 100558,
 100559,
 100560,
 100562,
 100563,
 100564,
 100565,
 100566,
 100567,
 100570,
 100571,
 100572,
 100573,
 100574,
 100575,
 100576,
 100577,
 100578,
 100579,
 100580,
 100581,
 100582,
 100583,
 100584,
 100585,
 100586,
 100587,
 100588,
 100589,
 100590,
 100593,
 100594,
 100595,
 100596,
 100597,
 100598,
 100599,
 100600,
 100601,
 100603,
 100604,
 100605,
 100606,
 100608,
 100609,
 100610,
 100611,
 100612,
 100614,
 100615,
 100616,
 100619,
 100620,
 100621,
 100623,
 100624,
 100626,
 100627,
 100628,
 100629,
 100630,
 100631,
 100632,
 100633,
 100634,
 100635,
 100636,
 100637,
 100638,
 100639,
 100640,
 100641,
 100642,
 100643,
 100644,
 100645,
 100646,
 100647,
 100648,
 100649,
 100650,
 100651,
 100652,
 100653,
 100654,
 100655,
 100656,
 100657,
 100658,
 100659,
 100660,
 100661,
 100662,
 100663,
 100664,
 100665,
 100666,
 100667,
 100668,
 100669,
 100670,
 100671,
 100672,
 100673,
 100674,
 100675,
 100676,
 100678,
 100679,
 100680,
 100681,
 100682,
 100683,
 100684,
 100685,
 100686,
 100687,
 100688,
 100689,
 100690,
 100691,
 100692,
 100693,
 100694,
 100695,
 100696,
 100697,
 100698,
 100700,
 100701,
 100703,
 100704,
 100705,
 100706,
 100707,
 100708,
 100709,
 100710,
 100712,
 100713,
 100714,
 100715,
 100716,
 100717,
 100718,
 100719,
 100720,
 100721,
 100722,
 100723,
 100724,
 100725,
 100726,
 100727,
 100728,
 100730,
 100731,
 100732,
 100733,
 100734,
 100735,
 100736,
 100737,
 100738,
 100739,
 100741,
 100742,
 100743,
 100746,
 100748,
 100749,
 100750,
 100755,
 100756,
 100757,
 100758,
 100759,
 100761,
 100764,
 100766,
 100767,
 100768,
 100769,
 100771,
 100773,
 100774,
 100775,
 100776,
 100778,
 100779,
 100780,
 100781,
 100782,
 100783,
 100784,
 100785,
 100786,
 100787,
 100788,
 100789,
 100790,
 100793,
 100794,
 100795,
 100796,
 100798,
 100799,
 100800,
 100801,
 100802,
 100803,
 100804,
 100805,
 100806,
 100807,
 100808,
 100809,
 100810,
 100811,
 100812,
 100813,
 100814,
 100815,
 100816,
 100817,
 100818,
 100819,
 100820,
 100821,
 100822,
 100824,
 100825,
 100827,
 100828,
 100829,
 100831,
 100832,
 100833,
 100834,
 100835,
 100837,
 100838,
 100839,
 100840,
 100841,
 100842,
 100843,
 100844,
 100845,
 100846,
 100847,
 100848,
 100849,
 100850,
 100851,
 100852,
 100853,
 100854,
 100855,
 100856,
 100857,
 100858,
 100859,
 100860,
 100861,
 100862,
 100863,
 100864,
 100865,
 100866,
 100867,
 100868,
 100869,
 100870,
 100871,
 100873,
 100874,
 100875,
 100876,
 100877,
 100878,
 100879,
 100880,
 100881,
 100882,
 100883,
 100884,
 100885,
 100886,
 100887,
 100888,
 100889,
 100890,
 100891,
 100892,
 100893,
 100894,
 100895,
 100896,
 100897,
 100898,
 100899,
 100900,
 100901,
 100902,
 100903,
 100904,
 100905,
 100906,
 100907,
 100908,
 100909,
 100911,
 100912,
 100914,
 100915,
 100916,
 100917,
 100919,
 100920,
 100921,
 100922,
 100923,
 100924,
 100925,
 100926,
 100927,
 100928,
 100929,
 100930,
 100932,
 100933,
 100934,
 100935,
 100936,
 100937,
 100938,
 100939,
 100940,
 100941,
 100942,
 100943,
 100944,
 100945,
 100946,
 100947,
 100948,
 100949,
 100950,
 100951,
 100954,
 100955,
 100956,
 100957,
 100958,
 100959,
 100960,
 100961,
 100962,
 100963,
 100964,
 100966,
 100967,
 100968,
 100969,
 100971,
 100972,
 100973,
 100974,
 100975,
 100976,
 100977,
 100978,
 100979,
 100980,
 100981,
 100985,
 100986,
 100988,
 100989,
 100990,
 100991,
 100992,
 100993,
 100994,
 100995,
 100996,
 100999,
 101000,
 101001,
 101003,
 101004,
 101006,
 101007,
 101009,
 101010,
 101011,
 101012,
 101013,
 101014,
 101015,
 101016,
 101017,
 101018,
 101019,
 101022,
 101023,
 101027,
 101028,
 101029,
 101030,
 101032,
 101033,
 101034,
 101035,
 101036,
 101037,
 101038,
 101039,
 101040,
 101042,
 101043,
 101044,
 101045,
 101046,
 101047,
 101048,
 101049,
 101050,
 101052,
 101053,
 101054,
 101058,
 101059,
 101060,
 101061,
 101062,
 101063,
 101065,
 101066,
 101067,
 101068,
 101069,
 101070,
 101071,
 101072,
 101073,
 101074,
 101075,
 101076,
 101077,
 101078,
 101080,
 101081,
 101082,
 101083,
 101084,
 101085,
 101086,
 101088,
 101089,
 101091,
 101093,
 101094,
 101095,
 101096,
 101098,
 101100,
 101101,
 101102,
 101103,
 101104,
 101105,
 101106,
 101108,
 101109,
 101110,
 101111,
 101112,
 101113,
 101114,
 101115,
 101116,
 101117,
 101119,
 101120,
 101121,
 101122,
 101123,
 101124,
 101127,
 101129,
 101130,
 101131,
 101132,
 101133,
 101134,
 101135,
 101137,
 101138,
 101139,
 101141,
 101142,
 101143,
 101144,
 101145,
 101146,
 101147,
 101148,
 101150,
 101151,
 101152,
 101153,
 101154,
 101155,
 101156]

In [76]:
df_bureau=bureaudata[bureaudata['SK_ID_CURR'].isin(currId)]
sorted(df_id_output['SK_ID_CURR'])

[100006,
 100006,
 100006,
 100006,
 100006,
 100006,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100011,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100021,
 100023,
 100023,
 100023,
 100023,
 100023,
 100023,
 100023,
 100023,
 100036,
 100036,
 100036,
 100036,
 100036,
 100036,
 100036,
 100036,
 100036,
 100036,
 100036,
 100036,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100043,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100047,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100048,
 100049,
 100049,
 100049,
 100049,
 100049,
 100049,
 100049,
 100049,
 100049,
 100049,
 100049,
 100049,
 100049,
 100050,
 100050,
 100050,
 100050,
 100050,
 100050,
 100050,
 100059,
 100059,
 100059,
 100059,
 100059,
 100059,
 100059,
 100059,
 100059,
 100059,
 100075,
 100075,
 100075,
 100075,
 100075,
 100075,
 100075,
 100075,
 100077,
 100077,
 100077,
 100077,
 100077,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100082,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100083,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100086,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100100,
 100101,
 100101,
 100101,
 100101,
 100101,
 100101,
 100101,
 100101,
 100101,
 100101,
 100101,
 100101,
 100101,
 100101,
 100110,
 100110,
 100110,
 100110,
 100110,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100112,
 100114,
 100114,
 100114,
 100114,
 100114,
 100114,
 100114,
 100115,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100116,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100131,
 100135,
 100135,
 100135,
 100135,
 100135,
 100135,
 100135,
 100135,
 100135,
 100135,
 100135,
 100135,
 100135,
 100135,
 100135,
 100135,
 100137,
 100137,
 100137,
 100137,
 100137,
 100137,
 100137,
 100137,
 100138,
 100138,
 100138,
 100138,
 100138,
 100138,
 100138,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100139,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100144,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100148,
 100151,
 100151,
 100151,
 100151,
 100151,
 100151,
 100151,
 100151,
 100151,
 100151,
 100151,
 100151,
 100151,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100152,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100153,
 100157,
 100157,
 100157,
 ...]

In [42]:
df_id_output.head()

,SK_ID_CURR,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
SK_ID_BUREAU,,,,,,,,,,,,,,,,
5715559,101060,Closed,currency 1,-1087,0,-874.0,-902.0,NaN,0,74242.80,0.00,NaN,0.0,Consumer credit,-711,NaN
5715560,101060,Active,currency 1,-709,0,783.0,NaN,NaN,0,395940.69,270998.82,NaN,0.0,Consumer credit,-7,NaN
5715561,101060,Active,currency 1,-886,0,479.0,NaN,NaN,0,270000.00,137875.50,0.0,0.0,Credit card,-26,NaN
5715564,101060,Closed,currency 1,-2632,0,-2478.0,-2541.0,0.0,0,76392.00,0.00,0.0,0.0,Consumer credit,-2539,NaN
5721463,100802,Active,currency 1,-525,0,928.0,NaN,NaN,0,157500.00,157630.50,0.0,0.0,Credit card,-25,NaN

In [77]:
currId=set(currId)
output=set(df_bureau['SK_ID_CURR'])

In [78]:
output - currId

set()

In [45]:
# currId=list(df_export['SK_ID_CURR'])
# currId
# df_id_output=data[data['SK_ID_CURR'].isin(currId)]

In [79]:
df_bureau.to_csv("graph_csv_1000k/bureau.csv",index=True,index_label="SK_ID_BUREAU:ID(Bureau)")

In [80]:
df_bureau.head()

,SK_ID_CURR,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
SK_ID_BUREAU,,,,,,,,,,,,,,,,
5715559,101060,Closed,currency 1,-1087,0,-874.0,-902.0,NaN,0,74242.80,0.00,NaN,0.0,Consumer credit,-711,NaN
5715560,101060,Active,currency 1,-709,0,783.0,NaN,NaN,0,395940.69,270998.82,NaN,0.0,Consumer credit,-7,NaN
5715561,101060,Active,currency 1,-886,0,479.0,NaN,NaN,0,270000.00,137875.50,0.0,0.0,Credit card,-26,NaN
5715564,101060,Closed,currency 1,-2632,0,-2478.0,-2541.0,0.0,0,76392.00,0.00,0.0,0.0,Consumer credit,-2539,NaN
5721463,100802,Active,currency 1,-525,0,928.0,NaN,NaN,0,157500.00,157630.50,0.0,0.0,Credit card,-25,NaN

# Bureau_balance.csv

In [34]:
balance=pd.read_csv("data/bureau_balance.csv")

In [81]:
currId=list(df_bureau.index)

In [82]:
currId

[5715559,
 5715560,
 5715561,
 5715564,
 5721463,
 5721932,
 5721933,
 5721934,
 5721936,
 5721937,
 5721938,
 5721939,
 5721940,
 5721941,
 5721943,
 5721944,
 5721945,
 5721946,
 5721947,
 5721948,
 5721949,
 5721950,
 5721952,
 5722930,
 5723577,
 5723578,
 5723579,
 5723580,
 5723581,
 5723582,
 5723583,
 5723952,
 5726282,
 5726283,
 5726284,
 5726285,
 5726286,
 5726287,
 5726288,
 6023751,
 6023752,
 6023753,
 6023754,
 6023755,
 6023756,
 6024123,
 6024124,
 6024126,
 6024127,
 6024128,
 6024129,
 6024130,
 6024131,
 5190197,
 5190198,
 5190199,
 5190200,
 5192775,
 5192776,
 5192777,
 5192778,
 5192779,
 5193383,
 5193384,
 5193385,
 5193810,
 5197113,
 5201794,
 5201795,
 5202357,
 5202358,
 5202359,
 5202361,
 5202362,
 5203458,
 5203459,
 5203460,
 5203462,
 5203463,
 5203464,
 5203465,
 5800488,
 5800489,
 5800490,
 5800491,
 5800492,
 5800493,
 5800494,
 5803711,
 5803712,
 5803713,
 5803714,
 5804273,
 5804274,
 5804275,
 5805498,
 5805499,
 5805500,
 5805501,
 5805502,
 5810660,
 5810661,
 5211678,
 5211679,
 5215386,
 5215387,
 5215485,
 5216097,
 5216211,
 5216212,
 5216213,
 5216214,
 5216215,
 5216216,
 5216217,
 5216219,
 5216220,
 5216221,
 5216222,
 5216223,
 5216225,
 5216496,
 5216497,
 5217355,
 5217356,
 5217357,
 5217358,
 5217359,
 5217360,
 5217422,
 5217423,
 5218529,
 5218530,
 5218531,
 5221676,
 5221677,
 5224501,
 5224502,
 5224503,
 5224505,
 5232893,
 5232894,
 5232895,
 5232897,
 5232898,
 5232899,
 5232900,
 5232901,
 5232902,
 5232903,
 5232904,
 5233085,
 5233086,
 5000924,
 5000925,
 5000926,
 5000928,
 5007958,
 5007959,
 5249947,
 5249948,
 5249949,
 5249950,
 5249952,
 5249953,
 5249954,
 5249955,
 5252103,
 5252104,
 5252105,
 5252106,
 5252107,
 5252108,
 5252109,
 5252398,
 5252399,
 5252400,
 5252401,
 5252402,
 5252404,
 5252405,
 5252406,
 5252407,
 5252408,
 5252410,
 5252445,
 5252446,
 5252447,
 5252448,
 5252449,
 5252451,
 5252452,
 5252453,
 5252454,
 5252455,
 5252456,
 5252457,
 5252458,
 5255038,
 5257920,
 5258038,
 5258039,
 5258040,
 5258042,
 5258043,
 5258044,
 5258045,
 5258046,
 5259395,
 5259396,
 5727772,
 5727773,
 5728772,
 5728773,
 5728774,
 5728777,
 5728778,
 5729560,
 5729561,
 5729563,
 5731023,
 5731024,
 5731025,
 5571153,
 5571161,
 5596101,
 5604250,
 5625644,
 5604427,
 5598119,
 5598127,
 5606018,
 5606024,
 5600576,
 5586543,
 5586551,
 5593924,
 5593928,
 5608101,
 5608106,
 5608178,
 5204900,
 5204901,
 5204902,
 5206730,
 5206731,
 5206733,
 5206734,
 5206736,
 5206737,
 5206740,
 6540753,
 6540754,
 6540755,
 6540756,
 6540757,
 6540758,
 6540759,
 6540761,
 6542258,
 6542259,
 6542261,
 6542262,
 6542263,
 6542264,
 6542408,
 6542409,
 6542410,
 6542411,
 6542412,
 6542414,
 6542415,
 6583903,
 6583905,
 6583906,
 6583907,
 6583908,
 6583909,
 6583910,
 6583911,
 6584419,
 6584420,
 6584421,
 6584423,
 6584424,
 6584860,
 6584861,
 6586625,
 6586626,
 6026868,
 6026869,
 6790637,
 6792337,
 6811365,
 6811912,
 5010495,
 5010496,
 5010497,
 5010498,
 5010499,
 5010500,
 5013715,
 5013716,
 5013717,
 5014473,
 5014474,
 5014476,
 5014477,
 5014478,
 5014479,
 6362423,
 6362424,
 6362425,
 6363403,
 6363404,
 6363405,
 6363480,
 6363481,
 6363482,
 6363483,
 6363484,
 5242675,
 5243481,
 5243482,
 5243483,
 5243484,
 5243485,
 5243486,
 5244757,
 5244759,
 5244760,
 5244761,
 5244762,
 5244763,
 5245639,
 5245640,
 5245641,
 5245643,
 5245645,
 5245646,
 5245647,
 5245648,
 5245649,
 6568287,
 6568288,
 5227431,
 5227438,
 5227439,
 5227440,
 5227441,
 5228926,
 5228928,
 5228929,
 5228930,
 6552703,
 6552704,
 6552705,
 6552706,
 6560507,
 6560508,
 6560509,
 6560834,
 6560835,
 6560836,
 6561924,
 6561925,
 6561926,
 6561927,
 6561928,
 6561929,
 6561930,
 6561931,
 6561933,
 6561934,
 6589773,
 6590717,
 6592742,
 6592743,
 6592744,
 6595625,
 6595626,
 6596638,
 5813386,
 5813388,
 5813389,
 5813390,
 5813452,
 5813453,
 5813454,
 5813455,
 5813456,
 5813457,
 5813459,
 5813460,
 5813461,
 5813462,
 5813786,
 5813787,
 5813859,
 6250979,
 6251519,
 6251520,
 6367370,
 6368824,
 6369180,
 6372721,
 6372722,
 5587305,
 5572560,
 5572569,
 5699084,
 5699085,
 5699087,
 5699088,
 5699595,
 5699596,
 5699597,
 5703953,
 5703954,
 5703955,
 5704884,
 5704885,
 5704886,
 5704887,
 5704888,
 5704889,
 5707074,
 5707075,
 5707076,
 5707077,
 5707078,
 5707079,
 5707080,
 5707340,
 5707341,
 5707342,
 5707343,
 5707344,
 6814607,
 6814609,
 6832139,
 6809189,
 6778677,
 6785836,
 5784403,
 5784404,
 5786498,
 5786499,
 5786500,
 5786502,
 6257963,
 6259931,
 6259933,
 6259934,
 6259935,
 6259936,
 6259938,
 6259939,
 6263561,
 6264250,
 6264251,
 5831158,
 5831160,
 5831161,
 5832095,
 5832096,
 5832412,
 5832413,
 5833458,
 5833459,
 5833460,
 5833461,
 5834194,
 5834195,
 5834196,
 5834197,
 5834198,
 5834233,
 5834234,
 5834235,
 5834236,
 5834237,
 5834240,
 5836417,
 5836418,
 5836419,
 5836421,
 5836422,
 5836423,
 5836424,
 5836425,
 5836426,
 5836427,
 5837511,
 5837512,
 5837513,
 5837514,
 5837515,
 5837516,
 5837517,
 6575293,
 6575294,
 6575497,
 6575498,
 6575499,
 6575501,
 6575502,
 6575503,
 6578571,
 6578572,
 6578573,
 6562811,
 6564951,
 6007161,
 6007162,
 6007163,
 6007164,
 6007165,
 6007166,
 6007451,
 6007452,
 5708257,
 5708258,
 5710748,
 5712867,
 5712868,
 5712869,
 5712943,
 5713669,
 5713670,
 5713671,
 5049123,
 5049124,
 5049125,
 5049127,
 5049128,
 5049129,
 5049130,
 5049132,
 5049133,
 5049134,
 5847045,
 5847294,
 5847295,
 5847469,
 5848357,
 5848360,
 5848361,
 5848363,
 5848365,
 5848366,
 5848367,
 5848368,
 5848369,
 5848629,
 5848630,
 5848631,
 5848632,
 5848634,
 5848635,
 5848636,
 5848637,
 5848638,
 5848849,
 5848851,
 5848852,
 5848853,
 5848854,
 5848855,
 5848858,
 5848859,
 5848860,
 5848861,
 5848862,
 5848863,
 5848864,
 5849414,
 5849415,
 5849416,
 5850762,
 5851500,
 5851502,
 5851503,
 5851504,
 5788692,
 5788693,
 5788694,
 5794974,
 5795752,
 5892073,
 5892074,
 5892075,
 5892290,
 5892291,
 5892969,
 5892970,
 5892971,
 5892972,
 5892975,
 5892976,
 5892977,
 5892978,
 5892979,
 5892980,
 5893242,
 5893245,
 5893246,
 5895457,
 5895458,
 5895459,
 5895460,
 5895462,
 5895463,
 5895464,
 5895465,
 5895466,
 5895467,
 5895468,
 5895469,
 5895471,
 5895472,
 5895473,
 5899217,
 5899218,
 5899219,
 5899220,
 5900043,
 5900044,
 5900045,
 5900046,
 5900047,
 5838978,
 5838979,
 5838980,
 5841297,
 5841298,
 5841299,
 5841300,
 5841301,
 5841302,
 5841303,
 5885306,
 5887533,
 5887538,
 5895461,
 5895470,
 5914139,
 5908497,
 5927075,
 5928810,
 5904977,
 5904981,
 5904999,
 5905004,
 5911710,
 5923851,
 5890011,
 5884489,
 5884490,
 5884491,
 5889106,
 5529419,
 5529420,
 5050848,
 5051154,
 5051155,
 5051156,
 5051157,
 5051158,
 5053117,
 5053118,
 5053119,
 5053120,
 5053121,
 5053122,
 5053123,
 5055101,
 5055102,
 5055999,
 5057753,
 5057755,
 5057756,
 5057757,
 5057758,
 5057759,
 5057760,
 5057761,
 5057763,
 5059219,
 5059220,
 5059222,
 5059254,
 5059255,
 5059256,
 5059257,
 5831157,
 5831159,
 5831162,
 5833457,
 5834238,
 5834239,
 5858588,
 5858589,
 5872205,
 5841295,
 5841296,
 5865772,
 5836420,
 5836428,
 5848359,
 5848633,
 5848850,
 5848857,
 5851501,
 5857948,
 5857949,
 5857950,
 5857951,
 5857961,
 5857964,
 5827033,
 5904153,
 5904154,
 5904155,
 5904975,
 5904976,
 5904978,
 5904979,
 5904980,
 5904982,
 5904983,
 5904984,
 5904985,
 5904986,
 5904987,
 5904988,
 5904989,
 5904990,
 5904992,
 5904993,
 5904994,
 5904995,
 5904996,
 5904997,
 5904998,
 5905000,
 5905001,
 5905002,
 5905003,
 5905005,
 5905006,
 6581401,
 6581402,
 6581403,
 6313108,
 6313109,
 6313110,
 6313112,
 6313113,
 6313114,
 6313115,
 6313116,
 6313178,
 6313179,
 6313180,
 6313181,
 6313182,
 6314850,
 6314851,
 6314853,
 6315872,
 6315874,
 6315875,
 6315876,
 6315877,
 6315878,
 6315879,
 6315880,
 5857939,
 5857940,
 5857942,
 5857943,
 5857944,
 5857945,
 5857946,
 5857947,
 5857952,
 5857953,
 5857954,
 5857955,
 5857956,
 5857957,
 5857958,
 5857959,
 5857960,
 5857962,
 5857963,
 5858577,
 5858578,
 5858579,
 5858580,
 5858581,
 5858582,
 5858583,
 5858584,
 5858585,
 5858586,
 5858587,
 6067202,
 6067315,
 6068075,
 6068545,
 6068554,
 6068559,
 6093292,
 6082080,
 6088074,
 6088076,
 6082822,
 6067203,
 6067204,
 6067205,
 6067206,
 6067207,
 6067208,
 6067310,
 6067311,
 6067312,
 6067313,
 6067314,
 6067316,
 6068070,
 6068071,
 6068072,
 6068073,
 6068074,
 6068076,
 6068546,
 6068547,
 6068548,
 6068549,
 6068550,
 6068551,
 6068552,
 6068553,
 6068555,
 6068556,
 6068557,
 6068558,
 6068560,
 6068561,
 6068562,
 6068563,
 6070534,
 5531774,
 5535234,
 5538710,
 5538711,
 5538713,
 5062259,
 5062260,
 6409599,
 6409600,
 6409601,
 6409602,
 6410924,
 6410925,
 6410975,
 6410976,
 6412706,
 6412707,
 6412708,
 6413841,
 6413842,
 6414000,
 6414001,
 6414002,
 6414003,
 6414004,
 6414005,
 6414006,
 6071565,
 6071566,
 6071568,
 6074160,
 6074191,
 6074216,
 5732162,
 5732163,
 5732164,
 5732198,
 5732199,
 5732200,
 5733577,
 5733923,
 5733924,
 5733925,
 5733926,
 5733927,
 5737003,
 5737424,
 5737426,
 5737427,
 5737428,
 5737700,
 5737701,
 5737702,
 6071567,
 6084936,
 6106468,
 6106474,
 6081550,
 5965789,
 5544327,
 5544329,
 5544330,
 5544331,
 5544332,
 5544333,
 5544334,
 5544335,
 6823732,
 6823733,
 6823734,
 6823778,
 6823779,
 6823780,
 6823781,
 6823782,
 6823783,
 6823784,
 6829119,
 6829133,
 6829134,
 6829600,
 6829601,
 6829602,
 6829603,
 6017772,
 5516650,
 5544328,
 5525783,
 5538712,
 5521387,
 5521388,
 5822152,
 5828442,
 6003066,
 6003067,
 6003068,
 6024125,
 6048314,
 6048315,
 6042221,
 6044396,
 6049851,
 5997916,
 5997919,
 5997920,
 5998182,
 5994529,
 5031317,
 5031319,
 5031320,
 5031321,
 5031322,
 5031323,
 5031324,
 5031325,
 5031326,
 5175490,
 5175492,
 5175493,
 5175494,
 5175495,
 5180713,
 5180714,
 6319237,
 6319238,
 6319239,
 6320709,
 5086751,
 5086752,
 5086753,
 5086754,
 5086755,
 5087518,
 5087519,
 5087520,
 6422120,
 6422121,
 6422829,
 6422830,
 6422831,
 6422832,
 6422833,
 6423388,
 6131357,
 6131359,
 6131360,
 ...]

In [83]:
df_bureau_bal=balance[balance['SK_ID_BUREAU'].isin(currId)]
df_bureau_bal

          SK_ID_BUREAU  MONTHS_BALANCE STATUS
81446          5228926             -47      C
81447          5228926             -48      C
81448          5228926             -49      C
81449          5228926             -50      C
81450          5228926             -51      C
81451          5228926             -52      0
81452          5228926             -53      X
81453          5228928               0      C
81454          5228928              -1      C
81455          5228928              -2      C
81456          5228928              -3      C
81457          5228928              -4      C
81458          5228928              -5      C
81459          5228928              -6      C
81460          5228928              -7      C
81461          5228928              -8      C
81462          5228928              -9      C
81463          5228928             -10      C
81464          5228928             -11      C
81465          5228928             -12      C
81466          5228928             -13      1
81467          5228928             -14      0
81468          5228928             -15      0
81469          5228928             -16      0
81470          5228928             -17      0
81471          5228928             -18      2
81472          5228928             -19      1
81473          5228928             -20      1
81474          5228928             -21      1
81475          5228928             -22      1
...                ...             ...    ...
27131649       6637793              -1      0
27131650       6637793              -2      0
27131651       6637793              -3      0
27131652       6637793              -4      0
27131653       6637795               0      0
27131654       6637795              -1      0
27131655       6637795              -2      0
27131656       6637795              -3      0
27131657       6637795              -4      0
27131658       6637795              -5      0
27131659       6637795              -6      0
27131660       6637795              -7      1
27131661       6637795              -8      0
27131662       6637795              -9      0
27131663       6637795             -10      0
27131664       6637795             -11      1
27131665       6637795             -12      0
27131666       6637795             -13      0
27131667       6637795             -14      0
27131668       6637795             -15      0
27131669       6637795             -16      0
27131670       6637795             -17      0
27131671       6637795             -18      0
27131672       6637795             -19      1
27131673       6637795             -20      0
27131674       6637795             -21      0
27131675       6637795             -22      0
27131676       6637795             -23      0
27131677       6637795             -24      0
27131678       6637795             -25      0

[43079 rows x 3 columns]

In [84]:
set(df_bureau_bal['SK_ID_BUREAU'])-set(currId)

set()

In [85]:
df_bureau_bal.to_csv('graph_csv_1000k/bureau_balance.csv',index=True,index_label="SK_ID_BUREAU:ID(Bureau_Balance)")

In [86]:
df_bureau_bal.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43079 entries, 81446 to 27131678
Data columns (total 3 columns):
SK_ID_BUREAU      43079 non-null int64
MONTHS_BALANCE    43079 non-null int64
STATUS            43079 non-null object
dtypes: int64(2), object(1)
memory usage: 1.3+ MB

# credit_card_balance.csv

In [57]:
credit=pd.read_csv("data/credit_card_balance.csv")

In [87]:
currId=list(df_prev['SK_ID_CURR'])
prevId=list(prev_data.index)

In [89]:
df_credit=credit[credit['SK_ID_CURR'].isin(currId)]

In [90]:
df_credit=df_credit[df_credit['SK_ID_PREV'].isin(prevId)]
df_credit

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
124,2306532,100796,-4,0.000,292500,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,41.0,Active,0,0
825,1375058,100662,-5,0.000,0,NaN,0.000,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
976,1727561,100218,-4,748180.935,720000,0.0,21073.905,0.0,21073.905,36990.450,...,741427.740,741427.740,0.0,8,0.0,8.0,8.0,Active,0,0
1149,2241207,100722,-1,0.000,0,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,7.0,Active,0,0
1363,1944493,101111,-4,0.000,0,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,3.0,Completed,0,0
1425,1060558,100048,-2,27302.400,225000,27000.0,27000.000,0.0,0.000,0.000,...,25956.900,25956.900,1.0,1,0.0,0.0,17.0,Active,0,0
2487,1880847,100135,-5,0.000,90000,NaN,0.000,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3266,2153525,100394,-4,0.000,405000,NaN,0.000,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Completed,0,0
3499,1787234,100059,-4,0.000,0,NaN,0.000,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Completed,0,0
3728,1683599,100942,-2,417874.545,450000,4500.0,4500.000,0.0,0.000,22286.250,...,416529.045,416529.045,1.0,1,0.0,0.0,40.0,Active,0,0
3954,1822938,100756,-5,0.000,67500,NaN,0.000,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
5252,1083054,100284,-19,0.000,450000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,6.0,Active,0,0
5257,2580197,100681,-20,0.000,45000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,64.0,Active,0,0
6423,1298506,100526,-3,0.000,135000,0.0,0.000,0.0,0.000,130.500,...,0.000,0.000,0.0,0,0.0,0.0,5.0,Active,0,0
6719,2306532,100796,-23,362278.710,450000,0.0,0.000,0.0,0.000,22500.000,...,362278.710,362278.710,0.0,0,0.0,0.0,25.0,Active,0,0
8212,2630110,100487,-65,17498.925,90000,0.0,0.000,0.0,0.000,4500.000,...,17498.925,17498.925,0.0,0,0.0,0.0,1.0,Active,0,0
8344,2843337,100307,-72,68165.640,67500,0.0,0.000,0.0,0.000,3375.000,...,68165.640,68165.640,0.0,0,0.0,0.0,12.0,Active,0,0
8561,1366401,100833,-66,70237.215,67500,4050.0,4050.000,0.0,0.000,3375.000,...,70237.215,70237.215,2.0,2,0.0,0.0,18.0,Active,0,0
8688,1298559,100338,-3,143379.405,180000,135000.0,141192.000,0.0,6192.000,0.000,...,138307.950,138307.950,3.0,5,0.0,2.0,10.0,Active,0,0
8886,2387337,100935,-7,186871.365,450000,0.0,0.000,0.0,0.000,10058.220,...,186871.365,186871.365,0.0,0,0.0,0.0,20.0,Active,0,0
10553,2409275,100296,-3,139534.065,135000,0.0,0.000,0.0,0.000,7046.775,...,137723.940,137723.940,0.0,0,0.0,0.0,3.0,Active,0,0
10760,1363286,100101,-2,419485.140,630000,225000.0,265386.915,0.0,40386.915,14617.845,...,419485.140,419485.140,1.0,9,0.0,8.0,11.0,Active,0,0
11280,1129322,101003,-4,403763.535,450000,0.0,0.000,0.0,0.000,20838.510,...,400784.850,400784.850,0.0,0,0.0,0.0,32.0,Active,0,0
11349,2592866,100418,-1,116629.155,135000,0.0,0.000,0.0,0.000,7355.565,...,116629.155,116629.155,0.0,0,0.0,0.0,31.0,Active,0,0
11411,1200971,100685,-3,299074.815,450000,0.0,0.000,0.0,0.000,15648.210,...,296872.920,296872.920,0.0,0,0.0,0.0,32.0,Active,0,0
12339,1595956,100100,-12,0.000,45000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,58.0,Active,0,0
12438,1282937,100861,-15,0.000,360000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,2.0,Active,0,0
12946,1682579,100906,-90,91330.290,180000,11250.0,11250.000,0.0,0.000,4500.000,...,91330.290,91330.290,1.0,1,0.0,0.0,4.0,Active,0,0
13491,1622722,100749,-34,0.000,90000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,2.0,Active,0,0
13658,2749257,100317,-35,340311.060,360000,0.0,0.000,0.0,0.000,17544.060,...,342925.695,342925.695,0.0,0,0.0,0.0,7.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3824399,2241207,100722,-46,0.000,0,0.0,0.000,0.0,0.000,0.000,...,-806.085,-806.085,0.0,0,0.0,0.0,7.0,Active,0,0
3824645,2445990,100362,-46,0.000,0,NaN,0.000,NaN,NaN,NaN,...,0.000,0.000,NaN,0,NaN,NaN,NaN,Active,0,0
3824674,2425075,101104,-48,0.000,90000,0.0,0.000,0.0,0.000,0.000,...,-272.925,-272.925,0.0,0,0.0,0.0,20.0,Active,0,0
3825523,1026684,100414,-81,45643.995,45000,0.0,0.000,0.0,0.000,2250.000,...,45643.995,45643.995,0.0,0,0.0,0.0,2.0,Active,0,0
3825580,1682579,100906,-74,0.000,180000,0.0,0.000,0.0,0.000,1587.060,...,0.000,0.000,0.0,0,0.0,0.0,20.0,Active,0,0
3826427,2044703,100345,-9,0.000,180000,NaN,0.000,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3826668,1547729,100940,-13,0.000,720000,NaN,0.000,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3827714,2527469,100165,-41,0.000,45000,NaN,0.000,NaN,NaN,NaN,...,0.000,0.000,NaN,0,NaN,NaN,NaN,Active,0,0
3828392,2188788,100519,-15,204981.435,450000,0.0,0.000,0.0,0.000,10887.480,...,204981.435,204981.435,0.0,0,0.0,0.0,7.0,Active,0,0
3830545,1487573,100814,-33,0.000,67500,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,4.0,Active,0,0
3831116,1556051,100220,-32,120933.990,180000,0.0,0.000,0.0,0.000,9000.000,...,120933.990,120933.990,0.0,0,0.0,0.0,40.0,Active,0,0
3831283,1418055,100993,-68,63948.600,67500,0.0,0.000,0.0,0.000,3375.000,...,63644.535,63644.535,0.0,0,0.0,0.0,14.0,Active,0,0
3831510,1383013,100853,-72,0.000,54000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,9.0,Active,0,0
3831576,2556918,100339,-68,161248.590,157500,0.0,0.000,0.0,0.000,7875.000,...,161248.590,161248.590,0.0,0,0.0,0.0,22.0,Active,0,0
3831670,1405242,101088,-73,175569.165,180000,0.0,0.000,0.0,0.000,9000.000,...,175569.165,175569.165,0.0,0,0.0,0.0,4.0,Active,0,0
3831854,2241207,100722,-71,0.000,135000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,7.0,Active,0,0
3832818,2833200,100468,-18,338415.210,450000,270000.0,270000.000,0.0,0.000,5155.020,...,336476.970,336476.970,2.0,2,0.0,0.0,11.0,Active,0,0
3833257,2837404,100865,-16,0.000,45000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,25.0,Active,0,0
3833954,1405242,101088,-59,0.000,180000,0.0,0.000,0.0,0.000,67.500,...,0.000,0.000,0.0,0,0.0,0.0,18.0,Active,0,0
3834029,1026684,100414,-60,46507.230,45000,2250.0,2250.000,0.0,0.000,2250.000,...,46507.230,46507.230,1.0,1,0.0,0.0,23.0,Active,0,0
3834554,1487573,100814,-31,0.000,67500,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,4.0,Active,0,0
3835188,1940618,100502,-31,0.000,157500,NaN,0.000,NaN,NaN,NaN,...,0.000,0.000,NaN,0,NaN,NaN,NaN,Active,0,0
3835731,2704651,100870,-27,135723.060,135000,0.0,0.000,0.0,0.000,6750.000,...,135723.060,135723.060,0.0,0,0.0,0.0,69.0,Active,0,0
3836035,2581692,100504,-28,69308.190,67500,4500.0,4500.000,0.0,0.000,3375.000,...,69308.190,69308.190,1.0,1,0.0,0.0,64.0,Active,0,0
3836244,2581692,100504,-27,68638.545,67500,0.0,0.000,0.0,0.000,3375.000,...,68638.545,68638.545,0.0,0,0.0,0.0,65.0,Active,0,0
3836314,1896725,100350,-28,0.000,67500,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,54.0,Active,0,0
3836458,1585412,101028,-26,0.000,90000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,8.0,Active,0,0
3836585,1772894,100900,-31,0.000,90000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,61.0,Active,0,0
3837909,2304765,100917,-67,174890.295,180000,90000.0,90000.000,0.0,0.000,9000.000,...,174890.295,174890.295,4.0,4,0.0,0.0,8.0,Active,0,0
3839994,2412736,100924,-10,130091.265,225000,0.0,0.000,0.0,0.000,7011.945,...,130091.265,130091.265,0.0,0,0.0,0.0,13.0,Active,0,0

In [91]:

df_credit.to_csv('graph_csv_1000k/credit_card_balance.csv',index=True,index_label="SK_ID_CURR:ID(CreditCardBal)")

In [93]:
a=set(df_id_output['SK_ID_PREV'])
c=set(prevId)
a-c

set()

# pos_cash_balance.csv

In [95]:
pos=pd.read_csv('data/pos_cash_balance.csv')

In [96]:
currId=list(df_prev['SK_ID_CURR'])
prevId=list(prev_data.index)

In [97]:
df_pos_cash=pos[pos['SK_ID_PREV'].isin(prevId)]
df_pos_cash=df_pos_cash[df_pos_cash['SK_ID_CURR'].isin(currId)]
df_pos_cash.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
183,2547775,100676,-41,24.0,12.0,Active,0,0
854,2687776,100457,-16,24.0,23.0,Active,0,0
1117,1653280,100442,-37,24.0,14.0,Active,0,0
1155,1474042,101037,-38,48.0,40.0,Active,0,0
1828,1364429,100525,-24,12.0,0.0,Completed,0,0

In [98]:
df_pos_cash.to_csv('graph_csv_1000k/pos_cash_balance.csv',index=True,index_label="SK_ID_CURR:ID(POS)")

In [99]:
df_pos_cash.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27971 entries, 183 to 10001201
Data columns (total 8 columns):
SK_ID_PREV               27971 non-null int64
SK_ID_CURR               27971 non-null int64
MONTHS_BALANCE           27971 non-null int64
CNT_INSTALMENT           27878 non-null float64
CNT_INSTALMENT_FUTURE    27878 non-null float64
NAME_CONTRACT_STATUS     27971 non-null object
SK_DPD                   27971 non-null int64
SK_DPD_DEF               27971 non-null int64
dtypes: float64(2), int64(5), object(1)
memory usage: 1.9+ MB

# installments_payments.csv

In [100]:
inst=pd.read_csv('data/installments_payments.csv')

In [101]:
df_inst=inst[inst['SK_ID_CURR'].isin(currId)]
df_inst=df_inst[df_inst['SK_ID_PREV'].isin(prevId)]

In [102]:
df_inst.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36288 entries, 14 to 3799665
Data columns (total 8 columns):
SK_ID_PREV                36288 non-null int64
SK_ID_CURR                36288 non-null int64
NUM_INSTALMENT_VERSION    36288 non-null float64
NUM_INSTALMENT_NUMBER     36288 non-null int64
DAYS_INSTALMENT           36288 non-null float64
DAYS_ENTRY_PAYMENT        36282 non-null float64
AMT_INSTALMENT            36288 non-null float64
AMT_PAYMENT               36282 non-null float64
dtypes: float64(5), int64(3)
memory usage: 2.5 MB

In [103]:

df_inst.to_csv('graph_csv_1000k/installments_payments.csv',index=True,index_label="SK_ID_CURR:ID(Installments_Payment)")

# RELATIONSHIPS

1. application-->previous_application
2. application-->bureau
3. bureau-->bureau_balance
4. application-->credit_card_balance
5. previous_application-->credit_card_balance
6. previous_application-->installments_payment
7. application-->installments_payment
8. application-->pos_cash_balance
9. previous_balance-->pos_cash_balance

In [ ]:
# 1. application-->previous_application
one=pd.read_csv('graph_csv_1000k/previous_application.csv')

In [105]:
oned=one[['SK_ID_CURR','SK_ID_PREV:ID(Previous_Application)']]
oned

      SK_ID_CURR  SK_ID_PREV:ID(Previous_Application)
0         100373                              1891648
1         100077                              2670402
2         101011                              1514511
3         100425                              1539382
4         100151                              1614986
5         100667                              1111156
6         100916                              1801757
7         100307                              2685304
8         100201                              2227969
9         100279                              2034342
10        100587                              1465837
11        100527                              1921372
12        100980                              1248695
13        100124                              1986247
14        101067                              1356683
15        100891                              1824766
16        100281                              1158695
17        101154                              1489082
18        100944                              1974762
19        100387                              1189722
20        100293                              1874254
21        100035                              1339797
22        101032                              2705391
23        101133                              1106193
24        100043                              1185699
25        100831                              2475428
26        100009                              1413109
27        100144                              1370544
28        100530                              2053202
29        100851                              1205384
...          ...                                  ...
4739      100846                              1983119
4740      100462                              1914680
4741      100325                              1198626
4742      100145                              2776540
4743      100577                              2245106
4744      100049                              1209367
4745      100078                              1025031
4746      100990                              1413303
4747      100451                              2742836
4748      100302                              1767081
4749      100980                              1100675
4750      100136                              1569850
4751      100748                              2835812
4752      101047                              2270834
4753      101028                              2787884
4754      100508                              1121595
4755      100971                              1651403
4756      101068                              1283248
4757      100093                              2708182
4758      100144                              1604951
4759      100662                              2645153
4760      100521                              2291632
4761      100594                              1516545
4762      100317                              2796174
4763      100148                              2570338
4764      100152                              2364400
4765      100779                              2095141
4766      100580                              1617498
4767      100166                              1139648
4768      100468                              2276384

[4769 rows x 2 columns]

In [106]:
oned.to_csv('graph_csv_1000k/curr_to_prev.csv',index=False,
            header=[":START_ID(Application)",":END_ID(Previous_Application)"])

In [107]:
# 2. application-->bureau
one=pd.read_csv('graph_csv_1000k/bureau.csv')
oned=one[['SK_ID_CURR','SK_ID_BUREAU:ID(Bureau)']]

oned.to_csv('graph_csv_1000k/curr_to_bureau.csv',index=False,
            header=[":START_ID(Application)",":END_ID(Bureau)"])

In [108]:
# 3. bureau-->bureau_balance
one=pd.read_csv('graph_csv_1000k/bureau_balance.csv')
one.head()

   SK_ID_BUREAU:ID(Bureau_Balance)  SK_ID_BUREAU  MONTHS_BALANCE STATUS
0                            81446       5228926             -47      C
1                            81447       5228926             -48      C
2                            81448       5228926             -49      C
3                            81449       5228926             -50      C
4                            81450       5228926             -51      C

In [109]:
oned=one[['SK_ID_BUREAU','SK_ID_BUREAU:ID(Bureau_Balance)']]

oned.to_csv('graph_csv_1000k/bureau_to_bureauBal.csv',index=False,
            header=[":START_ID(Bureau)",":END_ID(Bureau_Balance)"])

In [110]:
# 4. application-->credit_card_balance
# one=pd.read_csv('graph_csv_1000k/credit_card_balance.csv')
# one

# oned=one[['SK_ID_CURR','SK_ID_CURR:ID(CreditCardBal)']]

# oned.to_csv('graph_csv_1000k/curr_to_creditCardBal.csv',index=False,
#             header=[":START_ID(Application)",":END_ID(CreditCardBal)"])
# oned

In [112]:
# 5. previous_application-->credit_card_balance
one=pd.read_csv('graph_csv_1000k/credit_card_balance.csv')


oned=one[['SK_ID_PREV','SK_ID_CURR:ID(CreditCardBal)']]
oned
oned.to_csv('graph_csv_1000k/prev_to_creditCardBal.csv',index=False,
             header=[":START_ID(Previous_Application)",":END_ID(CreditCardBal)"])

In [113]:
# 6. previous_application-->installments_payment

one=pd.read_csv('graph_csv_1000k/installments_payments.csv')

one
oned=one[['SK_ID_PREV','SK_ID_CURR:ID(Installments_Payment)']]

oned.to_csv('graph_csv_1000k/prev_to_installment.csv',index=False,
            header=[":START_ID(Previous_Application)",":END_ID(Installments_Payment)"])

In [114]:
# 7. application-->installments_payment

# one=pd.read_csv('graph_csv_1000k/installments_payments.csv')

# one
# # one.head()
# oned=one[['SK_ID_CURR','SK_ID_CURR:ID(Installments_Payment)']]

# oned.to_csv('graph_csv_1000k/curr_to_installment.csv',index=False,
#             header=[":START_ID(Application)",":END_ID(Installments_Payment)"])

In [115]:
# 8. application-->pos_cash_balance
# one=pd.read_csv('graph_csv_1000k/pos_cash_balance.csv')

# oned=one[['SK_ID_CURR','SK_ID_CURR:ID(POS)']]

# oned.to_csv('graph_csv_1000k/curr_to_pos.csv',index=False,
#             header=[":START_ID(Application)",":END_ID(POS)"])

In [116]:
# 9. previous_balance-->pos_cash_balance
one=pd.read_csv('graph_csv_1000k/pos_cash_balance.csv')
one.head()
oned=one[['SK_ID_PREV','SK_ID_CURR:ID(POS)']]

oned.to_csv('graph_csv_1000k/prev_to_pos.csv',index=False,
            header=[":START_ID(Previous_Application)",":END_ID(POS)"])

bin\neo4j-admin.bat 
import --nodes:Application import/application.csv 
--nodes:Bureau import/bureau.csv
--nodes:Bureau_Balance  import/bureau_balance.csv
--nodes:CreditCardBal  import/cerdit_card_balance.csv
--nodes:Installments_Payment  import/installments_payments.csv
--nodes:POS  import/pos_cash_balance.csv
--nodes:Previous_Application  import/previous_application.csv
--relationships:HAS_PREVIOUS import/curr_to_prev.csv
--relationships:HAS_BUREAU  import/curr_to_bureau.csv
--relationships:CURR_CREDIT_BAL  import/curr_creditCardBal.csv
--relationships:PREV_CREDIT_BAL  import/prev_creditCardBal.csv
--relationships:HAS_CURR_INSTALLMENTS  import/curr_to_installment.csv
--relationships:HAS_PREV_INSTALLMENTS  import/prev_to_installment.csv
--relationships:HAS_CURR_POS import/curr_to_pos.csv
--relationships:HAS_PREV_POS import/prev_to_pos.csv
--relationships:HAS_BUREAU_BAL import/bureau_to_bureauBal.csv

In [ ]:
bin\neo4j-admin.bat import --nodes:CreditCardBal import/credit_card_balance.csv --nodes:Application import/application.csv --nodes:Bureau  import/bureau.csv --nodes:Bureau_Balance  import/bureau_balance.csv  --nodes:Installments_Payment  import/installments_payments.csv --nodes:POS  import/pos_cash_balance.csv --nodes:Previous_Application  import/previous_application.csv --relationships:HAS_PREVIOUS import/curr_to_prev.csv  --relationships:HAS_BUREAU  import/curr_to_bureau.csv  --relationships:CURR_CREDIT_BAL  import/curr_to_creditCardBal.csv   --relationships:HAS_CURR_INSTALLMENTS  import/curr_to_installment.csv --relationships:HAS_CURR_POS import/curr_to_pos.csv  --relationships:HAS_BUREAU_BAL import/bureau_to_bureauBal.csv --relationships:PREV_CREDIT_BAL  import/prev_to_creditCardBal.csv --relationships:HAS_PREV_INSTALLMENTS  import/prev_to_installment.csv --relationships:HAS_PREV_POS import/prev_to_pos.csv

    bin\neo4j-admin.bat import --nodes:CreditCardBal import/credit_card_balance.csv --nodes:Application import/application.csv --nodes:Bureau  import/bureau.csv --nodes:Bureau_Balance  import/bureau_balance.csv  --nodes:Installments_Payment  import/installments_payments.csv --nodes:POS  import/pos_cash_balance.csv --nodes:Previous_Application  import/previous_application.csv --relationships:HAS_PREVIOUS import/curr_to_prev.csv  --relationships:HAS_BUREAU  import/curr_to_bureau.csv  --relationships:CURR_CREDIT_BAL  import/curr_to_creditCardBal.csv   --relationships:HAS_CURR_INSTALLMENTS  import/curr_to_installment.csv --relationships:HAS_CURR_POS import/curr_to_pos.csv  --relationships:HAS_BUREAU_BAL import/bureau_to_bureauBal.csv

bin\neo4j-admin.bat import 
--nodes:Terms import/terms.csv 
--nodes:Work  import/workdetails.csv 
--nodes:Application  import/application.csv 
--nodes:Loansts  import/loanstatus.csv 
--nodes:Purpose  import/purpose.csv 
--nodes:Apptype  import/apptype.csv  
--nodes:Address  import/address.csv  
--nodes:Loan  import/loan.csv  
--relationships:WORKS  import/appid_to_workdetails.csv  
--relationships:LIVES  import/appid_to_address.csv  
--relationships:takes_loan  import/appid_to_loan.csv 
--relationships:loan_term import/appid_to_terms.csv 
--relationships:loan_status  import/appid_to_loanstatus.csv  
--relationships:application_purpose  import/appid_to_purpose.csv 
--relationships:application_type import/appid_to_apptype.csv

In [54]:
creditcard=pd.read_csv('graph_csv/credit_card_balance.csv')
creditcard

     SK_ID_CURR:ID(CreditCardBal) NAME_CONTRACT_STATUS  SK_ID_PREV  SK_ID_CURR
0                             124               Active     2306532      100796
1                             825               Active     1375058      100662
2                             976               Active     1727561      100218
3                            1149               Active     2241207      100722
4                            1363            Completed     1944493      101111
5                            1425               Active     1060558      100048
6                            2487               Active     1880847      100135
7                            3266            Completed     2153525      100394
8                            3484            Completed     2080876      100436
9                            3499            Completed     1787234      100059
10                           3728               Active     1683599      100942
11                           3954               Active     1822938      100756
12                           4354               Active     2659914      101141
13                           5252               Active     1083054      100284
14                           5257               Active     2580197      100681
15                           6064               Active     1331030      100902
16                           6423               Active     1298506      100526
17                           6719               Active     2306532      100796
18                           8212               Active     2630110      100487
19                           8344               Active     2843337      100307
20                           8561               Active     1366401      100833
21                           8688               Active     1298559      100338
22                           8886               Active     2387337      100935
23                          10148               Active     2659914      101141
24                          10553               Active     2409275      100296
25                          10760               Active     1363286      100101
26                          11280               Active     1129322      101003
27                          11349               Active     2592866      100418
28                          11411               Active     1200971      100685
29                          11835               Active     2445947      100948
..                            ...                  ...         ...         ...
970                        312214            Completed     1569638      100846
971                        312837            Completed     2556918      100339
972                        313648               Active     1682579      100906
973                        313770               Active     2682341      100336
974                        313952               Active     2094966      100880
975                        314144               Active     1974946      100957
976                        314379               Active     2304765      100917
977                        314436               Active     1516795      100712
978                        315622               Active     1739164      100514
979                        315919               Active     1410600      100621
980                        315988               Active     1137366      100914
981                        316336               Active     2761453      100629
982                        316547               Active     2155564      100453
983                        316630               Active     1928103      100364
984                        316992               Active     1974946      100957
985                        317122               Active     1374631      101059
986                        317284               Active     1381929      100493
987                        317788               Active     2581692      100504
988                        318356               Active     1331030      100902
989                        318455               Active     1490997      100505
990                        318462               Active     2659914      101141
991                        318645               Active     1395057      101006
992                        319717               Active     1424747      100515
993                        319764               Active     2843337      100307
994                        320313               Active     2304765      100917
995                        321198               Active     2704651      100870
996                        321226               Active     1516795      100712
997                        321229               Active     1871097      100224
998                        321755               Active     1017421      100198
999                        321758               Active     1026684      100414

[1000 rows x 4 columns]

# Instruction for upload:

1. Delete graph.db
2. Place files to the import folder
3. Run the script 
    For windows: use terminal from the neo4j desktop 
    For Linux: start a terminal from inside the import folder of neo4j from etc/neo4j
1. Expected '--nodes' to have at least 1 valid item, but had 0 []
    
    For this error, ensure that the files are at the correct folder